### ISSUE TITLE
Contribute with an event to TechNexus

### ISSUE THREAD

**Issue by pawarspeaks** [pawarspeaks/TechNexus#1]
Follow the steps in the `Readme.md` of the TechNexus respository and add an event to offline or virtual events code and create a pull request with help of the steps mentioned.

**Comment by kaushalkumar99** [comment]
Hi @pawarspeaks,
I'm on it...please assign this issue to me

**Comment by pawarspeaks** [comment]
@kaushalkumar99 assigned

**Comment by kaushalkumar99** [comment]
Hi @pawarspeaks,
done with adding new events...kindly merge the PR...thanks.

**Comment by anushka9555** [comment]
Can you please assign it to me?

**Comment by pawarspeaks** [comment]
Assigned @anushka9555

**Comment by AdityaGaur7** [comment]
can you assign this to me i have events idea on mind
