### ISSUE TITLE
Buttons overlap in mobile view 

### ISSUE THREAD

**Issue by SalehaTabassum** [pawarspeaks/TechNexus#103]
The buttons "Join the movements" and "Explore Events" overlap in mobile view.
I would like to make them responsive and remove this problem.
![Screenshot_2024-10-14-10-38-20-35_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/bb11a552-bf4f-4511-9164-2ae62f9b728d)

Please assign this issue to me and add the labels
@pawarspeaks

**Comment by anshulsoni2010** [comment]
I've already fixed this ui issue  #51 
![image](https://github.com/user-attachments/assets/b3e79ef2-7413-4cbd-af30-5288815dae2a)

**Comment by pawarspeaks** [comment]
Hey @SalehaTabassum thanks for raising this issue...actually this is done in another issue please find or raise a new issue that will enhance and uplift the platform for community.
Happy Opensourcing!🚀
