### ISSUE TITLE
Lost some icons in the footer

### ISSUE THREAD

**Issue by nethsaraPrabash** [pawarspeaks/TechNexus#105]
**Describe the bug**
In the footer of that application there are few icons added under the email but that does not shown due to some technical errors and missing libraries.

**To Reproduce**
1. Go to Technexus
2. Click on Home
3. Scroll down to Footer

**Expected behavior**
In here those icons seems to be added using font awesome and the library is not seems to be imported on the code file. Also in here I can see few errors on the code as well which prevents showing those icons.

**Screenshots**
Issue:
![Screenshot (95)](https://github.com/user-attachments/assets/5b198f0e-d592-4833-8f85-68663b13d542)
Code:
![Screenshot (96)](https://github.com/user-attachments/assets/4f10c345-d5ce-45d8-ab4c-ef2829705d7c)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version - -

**Smartphone (please complete the following information):**

**Additional context**
Please assign me to this issue and I'll fix that asap. Thank you for your understanding

**Comment by pawarspeaks** [comment]
@nethsaraPrabash thanks for raising this pr...assigned you.Please add a star to this repo and follow https://github.com/dev-Code-Community/ so that we can merge your PRs

**Comment by pawarspeaks** [comment]
resolved✅
