### ISSUE TITLE
Buttons Overlapping and Misaligned on Home Page for Mobile View

### ISSUE THREAD

**Issue by nirmitsaini1024** [pawarspeaks/TechNexus#109]
**Describe the bug**  
The buttons on the home page ("Join the Movement" and "Explore Events") are slightly overlapping and not properly centered within the div. This misalignment occurs when viewed on a Moto G14 mobile device.

**To Reproduce**  
1. Go to the Home page of the website.
2. Scroll down to the section with the "Join the Movement" and "Explore Events" buttons.
3. Observe that the buttons are overlapping slightly and not centered within the div.

**Expected behavior**  
The two buttons should be properly centered within the div, with no overlap between them. Both should be fully visible and aligned as intended for better user experience on mobile devices.

**Screenshots**  
Screenshot attached to illustrate the button overlap issue.

**Smartphone:**  
- Device: Moto G14  
- OS: Android 13  
- Browser: Brave  

**Additional context**  
The issue seems to be related to the responsive design for mobile devices, specifically on the Moto G14. Adjusting the button container or using media queries to optimize the layout might resolve the problem.

![Screenshot_20241015-084709.jpg](https://github.com/user-attachments/assets/d40fe024-8e92-4450-a47a-fd02558a31b9)

**Comment by nirmitsaini1024** [comment]
Hey @pawarspeaks @thepratappawar Please assign this issue to me, i fixed it in Localhost.
DESKTOP VERSION:
![376452122-d1f6c4cf-bfb1-4256-bf02-81102269cd91](https://github.com/user-attachments/assets/65883123-a273-422a-9101-3553e31c515b)
MOBILE VERSION FIXED:
![mmmmm](https://github.com/user-attachments/assets/f0cf59fe-c97f-4cc6-94af-26ef88e8e42e)

**Comment by anshulsoni2010** [comment]
Done at #51

**Comment by pawarspeaks** [comment]
@nirmitsaini1024 assigned kindly sync with the latest code commits on the main repo (we've a lot of changes today) and then get started..do link this issue while raising the PR

**Comment by pawarspeaks** [comment]
Resolved :)
