### ISSUE TITLE
Button Misalignment in Event Card Component

### ISSUE THREAD

**Issue by biplab-sutradhar** [pawarspeaks/TechNexus#110]
**Describe the bug**
The button is not vertically aligned with the "Learn More" link within the card component. It appears slightly higher than the link and should be aligned on the same level.

**To Reproduce**
1. Go to the event card component.
2. Observe that the button is misaligned, positioned slightly higher than the link and the link should be centered horizontally.

**Expected behavior**
The button should be vertically aligned with the "Learn More" link, both appearing on the same horizontal line.

**Screenshots**
 Before:
![image](https://github.com/user-attachments/assets/b97685b9-055a-4301-8c99-c49f26b3bf6c)
After:
![image](https://github.com/user-attachments/assets/60584486-3b8d-4de5-bdc3-a26ea7d2f91e)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - OS: [e.g. Android 13]
 
 **Additional context
  Please assign me this issue to fix

**Comment by AryanYadav-git** [comment]
@pawarspeaks assign this issue to me I've fixed the issue on the localhost.
![Screenshot 2024-10-15 211151](https://github.com/user-attachments/assets/a4efd401-a587-440e-a328-76439813a8ef)

**Comment by pawarspeaks** [comment]
@biplab-sutradhar please check out my comment on the raised PR...complete those steps and then I'll be able to merge it!

**Comment by pawarspeaks** [comment]
@AryanYadav-git this one is completed maybe raise a new one or add a few events to the platform?
