### ISSUE TITLE
Footer misalignment components

### ISSUE THREAD

**Issue by biplab-sutradhar** [pawarspeaks/TechNexus#113]
**Describe the bug**
The components in the footer are not aligned properly.

**To Reproduce**
1.Go to the footer component.
 2.Observe that the components are misaligned.

**Expected behavior**
Components should be aligned properly.

**Screenshots**
Before:
![image](https://github.com/user-attachments/assets/b4f86860-53a6-4f95-8dcf-6fbe9ceb6a70)
![image](https://github.com/user-attachments/assets/8d54438b-7bb1-4da1-a493-2df5d73cd885)
After:
![image](https://github.com/user-attachments/assets/2ca0e6c3-73a3-41fb-9715-b7f88967e1b4)
![image](https://github.com/user-attachments/assets/3424511b-8b21-4acd-ae38-77f99ba04a06)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - OS: [e.g. Android 13]

**Additional context**
  Please assign me this issue to fix

**Comment by anshulsoni2010** [comment]
Done at #51 so need for this issue

**Comment by pawarspeaks** [comment]
Resolved :)
