### ISSUE TITLE
[Performance] Implement Debounced Scroll Listener for Improved Performance in ScrollToTopButton Component

### ISSUE THREAD

**Issue by karthik-script** [pawarspeaks/TechNexus#123]
Hi @pawarspeaks, I can fix this issue for you. Please assign it to me.
Also, can you please add Labels on this for Hactoberfest? Thanks.

## Description: 
The current `ScrollToTopButton` component listens to the scroll event continuously, which can lead to performance issues due to frequent state updates. To improve performance, we need to debounce or throttle the scroll listener to reduce the frequency of calls to the `listenToScroll` function.

`src/components/ScrollToTopButton.jsx`

## Tasks:
1. **Implement Throttling/Debouncing:**
   - Use a library like `lodash.throttle` or `lodash.debounce` to limit the scroll event handling frequency.

2. **Test Performance:**
   - Verify that performance improves and the scroll-to-top functionality remains smooth across various scroll speeds.

## Benefits:
- **Improved Performance:** Reduced CPU load during scrolling.
- **Better User Experience:** Smooth and responsive scroll behavior.

**Comment by pawarspeaks** [comment]
@karthik-script assigned..do link this issue while raising the PR

**Comment by pawarspeaks** [comment]
hey @karthik-script are you on it?

**Comment by karthik-script** [comment]
Sorry for the delayed response.
