### ISSUE TITLE
Create Event page with third party map integration (OSM) to selection location from the embedded maps or manually enter the location. 

### ISSUE THREAD

**Issue by kaustubhdeokar** [pawarspeaks/TechNexus#127]
**Is your feature request related to a problem? Please describe.**
Creating new event. 

**Describe the solution you'd like**
Create a new page , with fields, embed a third party map, user should be able to drag the location on the map and point, or the user can enter the location acccording to the api queries : https://nominatim.org/release-docs/develop/api/Search/

**Describe alternatives you've considered**
Google maps - costly. 
OSM - free open source. 

**Additional context**

**Comment by kaustubhdeokar** [comment]
https://github.com/user-attachments/assets/1b7f3c84-c794-42d5-bdb2-c5f333729465

@pawarspeaks

**Comment by pawarspeaks** [comment]
resolved!✅
