### ISSUE TITLE
page breaks after resetting filters

### ISSUE THREAD

**Issue by vamsi4845** [pawarspeaks/TechNexus#133]
**Describe the bug**
Page Breaks when you click on the reset filters at the starting(without adding anything in filter)
**To Reproduce**
1. Go to 'events page'
2. Click on 'Reset Filters'
4. See error (page gets broken doesn't work even I refresh for 3-4 times)

**Screenshots**

https://github.com/user-attachments/assets/b5f58f82-5b4d-4bd0-8501-2a22162f5d39

**Expected behavior**
it should just reload on the same page,something like that without breaking
I've fixed it 

https://github.com/user-attachments/assets/3f9632ba-02aa-4144-92ed-c7500f6d0b83

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I want to work on this under hacktoberfest-accepted tag

**Comment by pawarspeaks** [comment]
@vamsi4845 assigned...please raise a pr by linking this issue whenever you do!
