### ISSUE TITLE
Adding a about us section

### ISSUE THREAD

**Issue by pushkar1713** [pawarspeaks/TechNexus#15]
I want to add a about us page next to contact us option, I think it will be a small but great addition

**Comment by pawarspeaks** [comment]
Hey our team option is already available right, we can list about us under that section too!

**Comment by pushkar1713** [comment]
Yeah nice Idea, I can make this work and add about us section above the contact us form?

**Comment by pawarspeaks** [comment]
sure assigned this issue to you! @pushkar1713

**Comment by pushkar1713** [comment]
Thanks @pawarspeaks
