### ISSUE TITLE
Break in Responsive on mobile versions

### ISSUE THREAD

**Issue by Pavan-Sai-padavala** [pawarspeaks/TechNexus#16]
When viewed on a mobile device, the application’s design appears disorganized. The application needs to be made responsive to enhance the user experience.
![image](https://github.com/pawarspeaks/TechNexus/assets/72682254/c047ffe6-b2be-4cb4-b8d1-0ea86395c74c)

**Comment by pawarspeaks** [comment]
@Pavan-Sai-padavala assigned you

**Comment by pranav-kale-01** [comment]
Hey! There aren't any pull requests for the issues yet, can I work on this issue?

**Comment by pawarspeaks** [comment]
@pranav-kale-01 create a new pull request and we'll merge if it is viewable on mobile devices
