### ISSUE TITLE
Copyright year missing in the footer section.

### ISSUE THREAD

**Issue by gauravsingh1281** [pawarspeaks/TechNexus#18]
<img width="958" alt="Screenshot 2023-10-14 235116" src="https://github.com/pawarspeaks/TechNexus/assets/85905403/bcf3390c-ca7f-4d21-bac5-25d800d2286d">

**Comment by gauravsingh1281** [comment]
@pawarspeaks Please assign this issue to me under hacktoberfest label.

**Comment by pawarspeaks** [comment]
@gauravsingh1281 assigned to you!
