### ISSUE TITLE
Favicon missing in Offline Events, Online Events, Our team and contact page.

### ISSUE THREAD

**Issue by gauravsingh1281** [pawarspeaks/TechNexus#31]
### Screenshots

<img width="955" alt="Screenshot 2023-10-18 163010" src="https://github.com/pawarspeaks/TechNexus/assets/85905403/77b3a60a-db48-40f3-a2a8-43a92fbc005c">
<img width="959" alt="Screenshot 2023-10-18 162933" src="https://github.com/pawarspeaks/TechNexus/assets/85905403/03e125a6-cfcd-4ca7-acfd-5b4a9b1b3355">
<img width="960" alt="Screenshot 2023-10-18 162905" src="https://github.com/pawarspeaks/TechNexus/assets/85905403/f534b0e7-cd04-4468-a4a8-c11826e0c8cd">
<img width="960" alt="Screenshot 2023-10-18 162835" src="https://github.com/pawarspeaks/TechNexus/assets/85905403/8b95cff7-1997-4896-b398-120a523b6286">

**Comment by gauravsingh1281** [comment]
@pawarspeaks Please assign this issue to me under hacktoberfest label.

**Comment by pawarspeaks** [comment]
@gauravsingh1281 assigned to you
