### ISSUE TITLE
more organized files

### ISSUE THREAD

**Issue by mr-mods-yg** [pawarspeaks/TechNexus#38]
when I first time saw TechNexus , I saw a lot of mess around and decided to fix it by organising all the files inside the folders.
it gives better readability to the user, by not affecting any piece of code.

## Organized Files
<img src="https://github.com/pawarspeaks/TechNexus/assets/62419230/db937ef4-04b1-4ebb-aa32-6fcfef46d08d" alt="Girl in a jacket" width="300" height="250">

**Comment by mr-mods-yg** [comment]
assign me so that i can resolve issues

**Comment by pawarspeaks** [comment]
@mr-mods-yg assigned, good luck!

**Comment by mr-mods-yg** [comment]
Can u check the pull now ?
