### ISSUE TITLE
Need for "Back to Top" Button

### ISSUE THREAD

**Issue by sambhavbohra** [pawarspeaks/TechNexus#52]
### Issue: Need for "Back to Top" Button

**Problem:**  
Users may experience difficulty when scrolling through long pages on the website. Without an easy way to navigate back to the top, the user experience can be frustrating, especially on mobile devices.

**Proposed Solution:**  
Implement a "Back to Top" button that allows users to quickly return to the top of the homepage with a single click.

**Steps to Implement:**
1. Add a button or icon to the bottom-right corner of the page that will remain visible when scrolling.
2. Use JavaScript or jQuery to add smooth scrolling functionality when the button is clicked, bringing the user back to the top of the page.
3. Style the button to ensure it is prominent but not intrusive on both desktop and mobile views.
4. Test across all pages to ensure the button behaves as expected.

**Expected Outcome:**  
The "Back to Top" button will provide users with a smoother navigation experience, enhancing overall usability, particularly on long pages.

**Comment by pawarspeaks** [comment]
Hi @sambhavbohra !
I've assigned this issue, you can start working on it!
Please raise a PR with '[Issue Number] feat: adding Back-to-top button'
Also do give this repo a ⭐
Happy Open Sourcing🚀

**Comment by TusharGupta-Developer** [comment]
"Hi @sambhavbohra , I would like to work on this issue. Could you please assign it to me? Thank you!"

**Comment by pawarspeaks** [comment]
Hey @TusharGupta-Developer this one is already assigned..maybe checkout some other issues or list a new one..or you can even simply list out a few events to the platform

**Comment by sambhavbohra** [comment]
The work is already done by so can i work on designing part

**Comment by pawarspeaks** [comment]
@sambhavbohra sure go ahead..please remember to raise a valuable issue..
