### ISSUE TITLE
Adding event list feature

### ISSUE THREAD

**Issue by kshitigambhir** [pawarspeaks/TechNexus#53]
![Screenshot 2024-10-12 171850](https://github.com/user-attachments/assets/e6b4c1a7-200d-4c5b-beff-ddb8599bf418)
Here  adropdown can be added whether the the event is online , offline or hybrid . can you pls assign this issue to me

**Comment by pawarspeaks** [comment]
Hi @kshitigambhir 
I've assigned this issue, you can start working on it!
Please raise a PR with '[Issue Number] feat: adding event list feature based on event mode (online/offline/hybrid)'
Also do give this repo a ⭐, to get you PRs merged
Happy Open Sourcing🚀

**Comment by TecHAyusH6476** [comment]
@pawarspeaks Please assign issue to me
