### ISSUE TITLE
Need to change of favicon and the title

### ISSUE THREAD

**Issue by Abhi-Jeeet** [pawarspeaks/TechNexus#54]
Your site is currently using the default title and favicon. To make it more representative of your project, we should customize both.

Could you please assign this task to update the favicon and set a new title that reflects your site’s purpose?

![Screenshot 2024-10-12 174404](https://github.com/user-attachments/assets/2cb5334a-0fc2-453d-b9d8-a682200d03e3)

**Comment by pawarspeaks** [comment]
Hi @Abhi-Jeeet !
I've assigned this issue, you can start working on it! Reach out to thepratappawar@gmail.com and I'll send you the relevant logo assets
Please raise a PR with '[Issue Number] feat: adding Favicon and title'
Also do give this repo a ⭐, to get you PR merged..
Happy Open Sourcing🚀

**Comment by Abhi-Jeeet** [comment]
@pawarspeaks 
I have sent you the mail, check that.

**Comment by pawarspeaks** [comment]
> @pawarspeaks I have sent you the mail, check that.

sent!

**Comment by Abhi-Jeeet** [comment]
Sure!!!

**Comment by pawarspeaks** [comment]
Resolved✅
