### ISSUE TITLE
Modern Navbar [improvement ]

### ISSUE THREAD

**Issue by MOHIT-IITP** [pawarspeaks/TechNexus#55]
I'd like to enhance the look of your navbar by updating it with a more modern UI design.
I want to change it to something like this, and with full matched color palette
![Screenshot 2024-10-12 at 6 33 49 PM](https://github.com/user-attachments/assets/9b1588aa-9530-4136-a663-c4e954d99722)

Assign me asap, i want to contribute to your project

**Comment by pawarspeaks** [comment]
Hi @MOHIT-IITP ... @anshulsoni2010 is already working on the UI so better if you both get connected and make PRs in ordered manners..

I've assigned this issue, you can start working on it!
Please raise a PR with '[Issue Number] feat: improving the Navbar'
Also do give this repo a ⭐, in order to get your PR merged
Happy Open Sourcing🚀

**Comment by anshulsoni2010** [comment]
Looks so simple!

Can we have it like this 👇 ? 
as in https://www.aperturs.com/
![image](https://github.com/user-attachments/assets/9bd0c3b1-35f4-4df2-8981-fcc11b5037e7)

**Comment by MOHIT-IITP** [comment]
Ok I will  make like that @anshulsoni2010

**Comment by anshulsoni2010** [comment]
Okay so work on this issue and improve it. can we know how much time you'll take to make it?

**Comment by MOHIT-IITP** [comment]
@anshulsoni2010 max 1 day

**Comment by MOHIT-IITP** [comment]
@anshulsoni2010 have you seen the navbar

**Comment by anshulsoni2010** [comment]
Um! I'll check it.

**Comment by anshulsoni2010** [comment]
Send me that screenshot, can't run the code right now.

**Comment by MOHIT-IITP** [comment]
@anshulsoni2010  check this out 
https://github.com/user-attachments/assets/3d95bea5-a5e5-497b-abb4-510f4a9580a6

**Comment by anshulsoni2010** [comment]
Great work man!! 

Merging PR :D

**Comment by MOHIT-IITP** [comment]
@anshulsoni2010  do you have discord (my username is : mohit_iitp2023)

**Comment by anshulsoni2010** [comment]
> It's not Responsive with different devices.

**Comment by anshulsoni2010** [comment]
> @anshulsoni2010  do you have discord (my username is : Mohit_iitp)

Okay, no need to talk on discord. 

It's fine to communicate here on GitHub

**Comment by anshulsoni2010** [comment]
@MOHIT-IITP improve the responsiveness.

**Comment by MOHIT-IITP** [comment]
@anshulsoni2010  checkout the latest commit , i have worked on the responsiveness.

**Comment by anshulsoni2010** [comment]
@pawarspeaks

**Comment by pawarspeaks** [comment]
@MOHIT-IITP please check my comment on pr
