### ISSUE TITLE
Implement a seperate  Contact Us page

### ISSUE THREAD

**Issue by RakinduM** [pawarspeaks/TechNexus#59]
Seperating contact us section from the footer would be make the website more UI rich. Consider and assign me to work on it.

**Comment by pawarspeaks** [comment]
@RakinduM That's a good one..please go ahead 
Happy Open sourcing!🚀

**Comment by Chhavi9700225780** [comment]
Assign it to me under hactoberfest 2024

**Comment by pawarspeaks** [comment]
> Assign it to me under hactoberfest 2024

Hey This one is assigned to someone...you can find other open issues or create a new if you find something that can be improved or implemented!
