### ISSUE TITLE
Change Default Tab Title from 'Vite + React' to Custom Site Title

### ISSUE THREAD

**Issue by TecHAyusH6476** [pawarspeaks/TechNexus#60]
**Issue:**
Currently, when a user opens the website, the browser tab shows "Vite + React" as the page title. This can be confusing and doesn’t reflect the branding of the website. It also misses an opportunity to reinforce the site identity and attract user attention.

![Screenshot 2024-10-12 203535](https://github.com/user-attachments/assets/da5e7daa-fd3d-4251-bfee-e6c3e8f75ca6)

**Solution:**
 I'd like to update the page title so that it displays the site name (e.g., "Tech Nexus") or the logo text. This title should be dynamic and reflect the brand consistently across all pages on the website. It would be ideal if we could also include a relevant title for each page or section, such as "Tech Nexus" on the homepage, and specific titles for other sections.

**Alternatives I've considered**
1. Manual HTML Title Update: Manually change the <title> tag in the index.html file in the public folder of the project. However, this would make the title static, which is not ideal for a dynamic application with multiple pages.
2. React Helmet: Use the react-helmet library to manage the document head dynamically, allowing each page or component to set its own title and metadata. This will provide flexibility and allow us to change the title dynamically based on the page content. 
3. Directly Update Document Title: Use document.title in React components. This would allow changing the title in useEffect for each page component but can be cumbersome to maintain.

**Additional context**
 Implementing this will help with SEO, making the website look more professional and branded. For example, on the "Meet Match" homepage, we could show "Meet Match - Your Source for Dating Advice" as the title. Here’s a mockup of how we might set it up with react-helmet

**Comment by pawarspeaks** [comment]
Hi @TecHAyusH6476 
Thank you so much for your new issue pointing out an important thing...
[Abhi-Jeeet](https://github.com/Abhi-Jeeet) is working on an similar issue (#54) better if you checkout his assigned issue and check what you can contribute over his contributions...if there is something..I'll assign this one to you.

Or else lets close this issue!
