### ISSUE TITLE
Missing Client-Side Validation for Email and Name Fields on Contact Us Section

### ISSUE THREAD

**Issue by TecHAyusH6476** [pawarspeaks/TechNexus#61]
**Description:**
Describe the bug The "Contact Us" section lacks client-side validation for the Email and Name fields. Users can submit the form with invalid or empty data, which could lead to incorrect information being recorded or submitted.

To Reproduce Steps to reproduce the behavior:

- Go to the "Contact Us" section.
- Click on the Email or Name field.
- Enter invalid data (e.g., non-email text in the Email field or leave fields blank).
- Attempt to submit the form.
- Observe that the form submits without validating the input fields.
- Expected behavior The Email and Name fields should be validated on the client side.

The Email field should require a valid email format.
The Name field should not be left blank. An error message should appear if these fields are not filled out correctly.
![Screenshot 2024-10-12 205259](https://github.com/user-attachments/assets/2b3f8435-3e9f-46b6-b4f6-71538d34b83a)

**Additional context**
 Implementing client-side validation can improve user experience and prevent incomplete or incorrect submissions.

**Comment by pawarspeaks** [comment]
Hey @TecHAyusH6476 
Thanks for the new issue!
![image](https://github.com/user-attachments/assets/0f63d4a0-8021-467d-b8a3-b7e8c41c69eb)
something like this is already implemented, could you please let me know what new validations can be done...and I'll assign this one to you.

Happy Open Sourcing!🚀

**Comment by TecHAyusH6476** [comment]
@pawarspeaks 
did we use any regex or just normal email validation?
If not I can implement regex implementation

**Comment by pawarspeaks** [comment]
@TecHAyusH6476 currently there is No Explicit Regex Validation...
you can work on it!
assigned to you. Do ⭐ repo and follow https://github.com/Dev-Code-Community to get your PR merged
Happy Open Sourcing!🚀

**Comment by TecHAyusH6476** [comment]
@pawarspeaks I have created PR for this issue

**Comment by pawarspeaks** [comment]
Resolved!
