### ISSUE TITLE
Footer enhancement

### ISSUE THREAD

**Issue by NiranjanKumar001** [pawarspeaks/TechNexus#62]
As we have people workin on new "contact us" section which is now in our footer section ,we will have to work on our footer too. so i would work on the footer and will be adding some more options so that it will look better and will have more content.Like our hacktoberfest site we could add share ,follow and legal subsection which will give it more professional look. @pawarspeaks .If  you like the suggestion please assign this to me.
![Screenshot 2024-10-12 211028](https://github.com/user-attachments/assets/6c2a1ae4-6634-4380-b72b-785b8aeaab10)

**Comment by pawarspeaks** [comment]
Hey @NiranjanKumar001 !
That's a good issue raised!
I've assigned this to you please start working and reach out to thepratappawar@gmail.com for any specific logo assets...please remember to highlight the Dev Code Community as initiating organization for this project...and keep the options in the footer concise.

**Comment by anshulsoni2010** [comment]
@NiranjanKumar001 are you working this issue?

**Comment by NiranjanKumar001** [comment]
> @NiranjanKumar001 are you working this issue?

@anshulsoni2010 already done waiting for author to come online and accept the PR

**Comment by anshulsoni2010** [comment]
Ohkkk

**Comment by pawarspeaks** [comment]
@NiranjanKumar001 kindly check the comment on pr and correct the social links
