### ISSUE TITLE
Website Responsiveness Issue

### ISSUE THREAD

**Issue by mayank-0789** [pawarspeaks/TechNexus#64]
# Website Responsiveness Issue

The website currently suffers from **irresponsiveness** due to the following reasons:

1. **Fixed Layout**: The layout does not adjust properly when viewed on different screen sizes (e.g., mobile, tablet, or desktop).
2. **Non-Scalable Text**: Font sizes are fixed and do not scale according to device or screen resolution.
3. **Images and Media**: Images and media elements are not responsive, and they overflow or are cut off on smaller screens.
4. **Viewport Not Set**: The `viewport` meta tag is missing or improperly configured, leading to poor display on mobile devices.
5. **Touch Event Handling**: Touch events are either poorly implemented or missing, affecting the usability on touch devices.

#screenshot

<img width="547" alt="Screenshot 2024-10-12 at 10 25 01 PM" src="https://github.com/user-attachments/assets/38e922c0-9c7c-4f54-8a03-498a2a28c211">

**Comment by pawarspeaks** [comment]
@mayank-0789 thanks for pointing this out..I've assigned you can get started working on it!
Please keep an eye and remember to sync the fork before raising PRs as multiple contributors are working on navbar and UI revamping.
Please make sure to follow https://github.com/Dev-Code-Community and star this repo⭐
to get your PR merged.

Happy Open Sourcing!🚀

**Comment by pawarspeaks** [comment]
Resolved✅
