### ISSUE TITLE
Feature  Request: Add Hamburger Menu for mobile devices and Improve Responsiveness

### ISSUE THREAD

**Issue by mohit-1710** [pawarspeaks/TechNexus#76]
# Feature  Request: Add Hamburger Menu for mobile devices and Improve Responsiveness

## Description

This pull request introduces a hamburger menu for mobile devices and addresses several responsiveness issues across the website. The goal is to enhance navigation on smaller screens and ensure that the layout adapts correctly to various device sizes.

## Changes Made

- **Hamburger Menu**: 
  - Implemented a responsive hamburger menu that collapses on mobile devices.
  - Added smooth transition effects for opening and closing the menu.
  - Ensured that the menu items are accessible and easy to use on touch devices.

- **Responsiveness Improvements**:
  - Fixed layout issues where elements were not displaying correctly on smaller screens.
  - Adjusted CSS styles using media queries for better alignment and spacing.
  - Tested the website on various screen sizes to identify and resolve remaining responsiveness issues.

### Responsiveness Issues

#button are not properly aligned and overlapping each other .

![image](https://github.com/user-attachments/assets/ee2bedb9-f46b-40ef-be75-e62a6957b941)

**Comment by mohit-1710** [comment]
please assign this issue to me .

**Comment by pawarspeaks** [comment]
Thanks for raising this @mohit-1710 !!
I've assigned it to kindly raise a PR linked to this issue in the format '[issue number] feat:  added hamburger menu for mobile devices and Improve responsiveness' 
Happy Open Sourcing!🚀

**Comment by pawarspeaks** [comment]
resolved!
