### ISSUE TITLE
Add Hover Effect to Expand 'Learn more' Button Size of online event tab

### ISSUE THREAD

**Issue by PragyaTripathi990** [pawarspeaks/TechNexus#80]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the 'Learn more' button in the online event tab doesn't visually change on hover, making the interface feel less interactive and dynamic.

**Describe the solution you'd like**
I want the 'Learn more' button to expand slightly when hovered over. This will provide better visual feedback and enhance the user experience by making the button feel more responsive.

**Describe alternatives you've considered**
Changing the button color on hover instead of expanding the size.
Adding a subtle shadow effect on hover instead of a size increase.

**Additional context**
Adding the hover effect with smooth transitions will keep the user interface fluid. 
<img width="1449" alt="Screenshot 2024-10-13 at 6 48 37 AM" src="https://github.com/user-attachments/assets/ba565f17-fb4d-423e-960f-9deccb164b7f">

**Comment by pawarspeaks** [comment]
Hey @PragyaTripathi990 thanks for raising but just adding a hover effect might get rejected in hacktoberfest reviews...may be improve some UI or contribute with events as guided in readme.md file?
