### ISSUE TITLE
ADD EVENT AS PLACEMENT PREP FOR STUDENTS

### ISSUE THREAD

**Issue by Swastik200** [pawarspeaks/TechNexus#82]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
TO INSPIRE STUDENT BY PROVIDING FULL PATH FOR PLACEMENT

**Describe alternatives you've considered**

**Additional context**

**Comment by pawarspeaks** [comment]
maybe you've pasted something irrelevant..closing this one
