### ISSUE TITLE
Adding reset filter button in the event list page 

### ISSUE THREAD

**Issue by Keerthi-k6** [pawarspeaks/TechNexus#84]
**Is your feature request related to a problem? Please describe.**
The event list page has a filter button , but there is not reset button . Users have to clear out the filters always in order to make new filters 

**Describe the solution you'd like**
add a reset filter button that resets the filters and loads the page to its default state 

**Describe alternatives you've considered**
Enhance the whole filter mechanism of the event list page

**Comment by Keerthi-k6** [comment]
@pawarspeaks  can you please assign this issue to me , i would like to contribute

**Comment by pawarspeaks** [comment]
@Keerthi-k6 assigned!

**Comment by Keerthi-k6** [comment]
@pawarspeaks  I have raised a new pr , please check

**Comment by pawarspeaks** [comment]
resolved!
