### ISSUE TITLE
Adding Hover Effect to the "Learn More" Button

### ISSUE THREAD

**Issue by ShrutiDesai7** [pawarspeaks/TechNexus#85]
I was exploring the project and noticed that while the buttons have hover effects, the "Learn More" button doesn't currently have one. I'd love to contribute by adding a consistent hover effect to that button to enhance the user experience.

Could I take this on? Let me know if this aligns with your current plans for the project!

**Comment by pawarspeaks** [comment]
Hey @ShrutiDesai7 that would be good but a very minor contribution maybe you could improve any more components..so that it doesn't get rejected in hacktobefest

**Comment by pawarspeaks** [comment]
let me know and I'll assign

**Comment by ShrutiDesai7** [comment]
Okay. Thanks for sharing your opinion.

**Comment by anshulsoni2010** [comment]
Doesn't makes sense by just adding effect to the button.
