### ISSUE TITLE
Date Format Inconsistency and Event Filtering Issues on Event List Page

### ISSUE THREAD

**Issue by Keerthi-k6** [pawarspeaks/TechNexus#86]
**Describe the bug**
The event list page has start date and end date filter , which is in the format of dd-mm-yyyy , but the dates displayed are in mm-dd-yyyy format . this creates confusion to the user , who wants to search for a event that falls in range with other events . Also there is an non functional apply filter button , even though the filters work on change of the event .  There is redundant code in the code base that has to be removed .

**To Reproduce**
1. Go to Event List Page  
2. fill in the start date and end date filter 
3. Scroll down to check the events that lie in the range 
4. you will not be able to see any events  as the user thinks the dates that are displayed in the cards are in the format of dd-mm-yyyy

**Expected behavior**
Page shall the dates in the format of dd-mm-yyyy 
remove apply filters button 

**Alternative Suggestions **
adding the filter of name , which helps in searching events based on the name of the event can be more user friendly 

**Screenshots**
<img width="926" alt="image" src="https://github.com/user-attachments/assets/ceec8325-14c8-4103-94ee-3a84770d6714">
![date filter](https://github.com/user-attachments/assets/b8504ad6-95ed-45d9-a1ec-8a5107265523)

**Comment by Keerthi-k6** [comment]
@pawarspeaks can you please check this issue and assign it to me

**Comment by pawarspeaks** [comment]
Hey @Keerthi-k6 thanks for raising this one!
![image](https://github.com/user-attachments/assets/2603cc3b-f6c2-4f18-910b-e0329c50a417)

the filter works properly but you are right filter is in dd/mm/yyyy format but the event data that we are collecting is in the mm/dd/yyyy format.
It would be great if you could do the following:
1] converting all current events (there are very few events rn so this is possible) format to dd/mm/yyyy
2] correcting of the function that lists the events from the online and offline event data json files to fetch and display in the dd/mm/yyyy format.
3] Post that thee's something more that we need currently...we need there to be a proper teomplate and commented out guideline in both event data json files from which contributors can copy the template and know whether to add their event to the top of json or bottom.
4] Also the last one is that currently while many contributors are raising PR's at the same time so the id number in multiple PR builds merging conflicts it could be great if can do something for avoiding such conflicts ahead...may be doing something with the 'id' can help.


let me know if you can alone do this one or I'll assign someone to collaborate with you

**Comment by Keerthi-k6** [comment]
yeah , i can do this alone. also i have updated a new suggestion , of adding the name of the event as a filter . Let me know if this works

**Comment by pawarspeaks** [comment]
Awesome you can do the name search too..take your time!
Happy Open Sourcing!🚀

**Comment by Keerthi-k6** [comment]
can you please check the other issue i have raised abouut the filter reset button

**Comment by Villain45** [comment]
@pawarspeaks @Keerthi-k6 I can help in this issue

**Comment by Keerthi-k6** [comment]
I have already worked upon the 2) correcting of the function that lists the events from the online and offline event data json files to fetch and display in the dd/mm/yyyy format. we don't exactly need to correct the current json data files instead , I made the function to take no matter what date format and display it in dd-mm-yyy . this reduces the manual work that needs to done for 1) in the list . @pawarspeaks

**Comment by pawarspeaks** [comment]
> I have already worked upon the 2) correcting of the function that lists the events from the online and offline event data json files to fetch and display in the dd/mm/yyyy format. we don't exactly need to correct the current json data files instead , I made the function to take no matter what date format and display it in dd-mm-yyy . this reduces the manual work that needs to done for 1) in the list . @pawarspeaks

Cool! that works even better

**Comment by Keerthi-k6** [comment]
@Villain45  , I am almost done with this issue .

**Comment by pawarspeaks** [comment]
@Villain45 cool then you can contribute to the 3rd one and the event sorting thing you mentioned!

**Comment by pawarspeaks** [comment]
assigned to both of you @Villain45 @Keerthi-k6

**Comment by Villain45** [comment]
@pawarspeaks can you elaborate more on 3]? does it matter whether it is top or bottom? things will be fine if we sort events according to date

**Comment by pawarspeaks** [comment]
> @pawarspeaks can you elaborate more on 3]? does it matter whether it is top or bottom? things will be fine if we sort events according to date

yeah sorting events on the platform is cool...but what issue we are facing with unique id's is some contributors add events to top (changing all other ids with +1 or so) and some post them at the end...so having some system like without id and just events not matter id...or either proper contribution guide in the json files itself..

**Comment by Villain45** [comment]
@pawarspeaks Ok got it, didn't see that data was from json and has id's 😅, will remove dependency on id
Will start working once the PR is merged

**Comment by Keerthi-k6** [comment]
@pawarspeaks @Villain45  , even if we don't pass the unique id , it wont break the react code . However issue occurs when we try to implement something like delete. So we can completely omit passing key prop as long as we are not implementing anything that is id dependent like delete . We can create a json template and ask the pr owners to follow it for now

**Comment by pawarspeaks** [comment]
> @pawarspeaks Ok got it, didn't see that data was from json and has id's 😅, will remove dependency on id Will start working once the other PR is merged

Sure works...do consider @Keerthi-k6 's suggestion acutally @Keerthi-k6 its not breaking codes but is makes merge conflicts ..so may be just giving the template within files would work

**Comment by Keerthi-k6** [comment]
@pawarspeaks @Villain45  I have raised my pr , please check

**Comment by Villain45** [comment]
@pawarspeaks isn't it better to remove dependency of id?

**Comment by Keerthi-k6** [comment]
@Villain45  I don't think removing the id from the json files is a good idea, because in future if we were to implement backend or any other features , id would be a good key to perform operations like delete , favorite etc .

**Comment by Villain45** [comment]
@Keerthi-k6 when backend is implemented the db which will be used will provide id for each event inserted into it, at that time it can be replaced easily, currently there will be conflicts if we have id dependency, and also to perform things like delete and all, it is sure that we need db

**Comment by Keerthi-k6** [comment]
@Villain45 , Sorry I didn't exactly get what u are trying to say

**Comment by Villain45** [comment]
> @Villain45 I don't think removing the id from the json files is a good idea, because in future if we were to implement backend or any other features , id would be a good key to perform operations like delete , favorite etc .

why we need id when backend will be implemented? the database provides id for each record when inserted into it

**Comment by Keerthi-k6** [comment]
> > @Villain45 I don't think removing the id from the json files is a good idea, because in future if we were to implement backend or any other features , id would be a good key to perform operations like delete , favorite etc .
> 
> why we need id when backend will be implemented? the database provides id for each record when inserted into it

Makes sense , but for now , in my other pr , i need that id. Because I implemented favorites feature using local storage and context . So i dont think thats a good idea , rather , just giving a json template with instructions to user shall suffice

**Comment by Villain45** [comment]
Ohk, now I clearly make sense why is that not a good idea...
Then main thing of removal of id dependency was conflict issue, can you elaborate how can a json template overcome this? when there are multiple people making multiple PR on events

You know what let it be if @pawarspeaks wants me to remove will remove it.

**Comment by pawarspeaks** [comment]
> > > @Villain45 I don't think removing the id from the json files is a good idea, because in future if we were to implement backend or any other features , id would be a good key to perform operations like delete , favorite etc .
> > 
> > 
> > why we need id when backend will be implemented? the database provides id for each record when inserted into it
> 
> Makes sense , but for now , in my other pr , i need that id. Because I implemented favorites feature using local storage and context . So i dont think thats a good idea , rather , just giving a json template with instructions to user shall suffice

@Villain45 @Keerthi-k6 I just now merged the pr for the favorites thing storing locally...so @Villain45 I'll merge your date sorting code and remove other...Thanks both of you!⭐
(ps: backend is being implemented and id will be removed once its live..till then let us use it)
insist both of you joining: https://discord.gg/G2acRSSdhX
where we'll be discussing the future scope for community contributions for the TechNexus platform!
