### ISSUE TITLE
[Feature] Sorting events by date

### ISSUE THREAD

**Issue by Villain45** [pawarspeaks/TechNexus#87]
Can we add a feature where users can sorts the events according to the upcoming event date?, basically events according to date ascending and descending....
Would like to work on this

By the way nice project...

**Comment by pawarspeaks** [comment]
Hey @Villain45 Thanks for raising this one! and thanks for the compliment :)
There is a date filter to find events within a particular time range...
If you are looking into something more you can checkout #86 maybe the contributor there and you can collaborate and I'll assign you both the same issue...I've also listed out all the requirements regarding this date filtering.
Thanks..

**Comment by Villain45** [comment]
@pawarspeaks Actually here i was talking about sorting filter to know which events are the earliest and all, the filter you are talking about is to find events in a custom date range

**Comment by pawarspeaks** [comment]
How about moving things to that issue itselft @Villain45 so we dont have conflict while merging...let her push and then maybe we can merge yours...please post a message what you'll be working on in that issue i'll assign to you too

**Comment by Villain45** [comment]
@pawarspeaks it seems that issue is almost complete, In case if you don't want merge conflicts I will start working once that issue is merged

**Comment by pawarspeaks** [comment]
@Villain45 sure its assigned to you keep an eye maybe once she pushes her final PR and once merged..you can start🚀
