### ISSUE TITLE
Optimise Design of Contact Us Form

### ISSUE THREAD

**Issue by bhaveshgarg2000** [pawarspeaks/TechNexus#9]
Hii @pawarspeaks Please assign me this I would like to contribute to this.....

**Comment by pawarspeaks** [comment]
Assigned!

**Comment by bhaveshgarg2000** [comment]
Thanks @pawarspeaks

**Comment by pawarspeaks** [comment]
@bhaveshgarg2000 are you working on it?

**Comment by AdityaGaur7** [comment]
please assign this to me I wanna work on this

**Comment by bhaveshgarg2000** [comment]
@pawarspeaks Assign to someone else
Thank You
