### ISSUE TITLE
 ScrollReveal Animations 

### ISSUE THREAD

**Issue by TusharGupta-Developer** [pawarspeaks/TechNexus#92]
### Problem:
The React application currently lacks dynamic scroll-based animations, leading to a static and less engaging user interface.

### Solution:
Integrate `ScrollReveal.js` to implement smooth, scroll-triggered animations across key components.

### Benefits:
- **Enhanced Interaction**: Engages users by drawing attention to specific sections as they scroll.
- **Modern UI**: Adds a dynamic and polished feel to the application.

### Steps:
1. Install `ScrollReveal` using npm: `npm install scrollreveal`.
2. Initialize `ScrollReveal` in the required React components.
3. Apply animations to target elements using `useEffect`.

This will improve user experience by introducing smooth, engaging animations tailored to React components.

**Comment by TusharGupta-Developer** [comment]
Hi @pawarspeaks, could you please add the `hacktoberfest` label to this issue and assign it to me? I would love to work on it. Thank you!

**Comment by anshulsoni2010** [comment]
I am working on that #51

**Comment by anshulsoni2010** [comment]
This is already done at #51

**Comment by pawarspeaks** [comment]
@TusharGupta-Developer we have another contributor who is working on a ui revamp may be you can find the other other listed issues or raise one.
Thanks!
