### ISSUE TITLE
Add first and last buttons to pagination that helps the user to navigate through pages , if there are a lot of events 

### ISSUE THREAD

**Issue by Keerthi-k6** [pawarspeaks/TechNexus#94]
**Is your feature request related to a problem? Please describe.**
 A lot of pages can make time user have a hard time navigating through a ton of events . Adding  first and last buttons to pagination that helps the user to navigate through pages , if there are a lot of events 

**Describe the solution you'd like**
Add first and last buttons in the pagination

**Comment by Keerthi-k6** [comment]
@pawarspeaks  I have worked upon this issue . Please assign it to me , thanks in advance

**Comment by pawarspeaks** [comment]
resolved!
