### ISSUE TITLE
Add Favorites button to event card

### ISSUE THREAD

**Issue by Keerthi-k6** [pawarspeaks/TechNexus#97]
**Is your feature request related to a problem? Please describe.**
Adding a favorites button would help me see all the events I want to go through  at a same place 

**Describe the solution you'd like**
Add Favorites button to event card , so that user can book mark all the events he/ she wants at once

**Comment by Keerthi-k6** [comment]
@pawarspeaks I have worked on this issue , please assign it to me

**Comment by Keerthi-k6** [comment]
@pawarspeaks . I have raise a pr for this issue , please review

**Comment by anshulsoni2010** [comment]
Btw, it's just a frontend website so where you'll be storing the favourite events?

**Comment by Keerthi-k6** [comment]
Local storage , once if we have the backed , we can implement it through login etc

**Comment by anshulsoni2010** [comment]
ah, i think that's not making the sense. this feature is not worth it. you can look up to another issues made by @pawarspeaks which are actually worth it and ya should work on.

**Comment by Keerthi-k6** [comment]
Well , if there are a lot of events  and you want to choose some of them , I think this will make sense because , as mentioned in the issue , you would want to see them all together at one place . Anyway I have already raised the pr , let @pawarspeaks  decide

**Comment by anshulsoni2010** [comment]
@Keerthi-k6 I just have chat with @pawarspeaks

You can start working on this and you'll be assigned very soon for this issue. 

Let us know if you need any assistance while developing this feature.

**Comment by Keerthi-k6** [comment]
I have already raised the PR - #98  , you can check it after assigning this issue to me. Also , I have raised  PR- #95 for issue #94  and pr - #90 for the issue #84  . Please take a look at them.

**Comment by pawarspeaks** [comment]
resolved!
